options:
  formatter: stylish
  verbose: true

files:
  include: 'src/scss/**/*.scss'

rules:
  indentation:
    - 2
    - size: 2
  property-sort-order:
    - 2
    - order: 'recess'
      ignore-custom-properties: true
