version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - '9090:80'
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      PHP_ENV:
    volumes:
      - ./theme:/var/www/html/wp-content/themes/threeforflavin
  db:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
